/**
 * AVIS+ — Référentiel des catégories d'entreprises.
 *
 * Source : `categorie.md` (catégories d'entreprises à prospecter à Ouagadougou).
 * Ce référentiel sert à **classer les pages digitales** : chaque entreprise est
 * rattachée à une catégorie principale et, si utile, à une sous-catégorie précise.
 *
 * Note sur la fidélité au document source :
 * - Les sections 1 à 20 de `categorie.md` sont reprises telles quelles.
 * - La section 1 (« Priorité maximale ») regroupe six activités distinctes : elles
 *   sont éclatées en catégories autonomes (Restauration, Hôtellerie, Beauté, Mode,
 *   Cosmétiques, Commerces spécialisés) car c'est ainsi qu'un commerçant se reconnaît.
 * - La section 18 (« Mode et beauté — sous-segment spécialisé ») est un sous-ensemble
 *   de « Beauté et soins esthétiques » : ses entrées ont été fusionnées pour éviter
 *   deux catégories beauté concurrentes dans l'interface.
 * - Les groupes de priorité commerciale A / B / C du document sont conservés dans le
 *   champ `priority`, à titre indicatif.
 */

/** Groupe d'effort commercial défini dans `categorie.md`. */
export type CategoryPriority = "A" | "B" | "C";

export interface BusinessCategoryDef {
  /** Identifiant stable, utilisé en base et dans les URL de filtre. */
  id: string;
  /** Libellé affiché dans l'interface. */
  label: string;
  /** Phrase courte expliquant ce que regroupe la catégorie. */
  description: string;
  /** Priorité commerciale indicative (`categorie.md`). */
  priority: CategoryPriority;
  /** Sous-catégories proposées à la saisie. */
  subcategories: readonly string[];
}

/* -------------------------------------------------------------------------- */
/* Référentiel                                                                */
/* -------------------------------------------------------------------------- */

export const BUSINESS_CATEGORIES: readonly BusinessCategoryDef[] = [
  {
    id: "restauration",
    label: "Restauration",
    description: "Restaurants, maquis, bars, cafés, boulangeries et traiteurs.",
    priority: "A",
    subcategories: [
      "Restaurants",
      "Fast-foods",
      "Pizzerias",
      "Bars",
      "Lounges",
      "Cafés",
      "Coffee shops",
      "Maquis",
      "Grillades",
      "Snack-bars",
      "Food trucks",
      "Traiteurs",
      "Boulangeries",
      "Pâtisseries",
      "Chocolateries",
      "Glaciers",
      "Restaurants spécialisés",
      "Restaurants-hôtels",
    ],
  },
  {
    id: "hotellerie",
    label: "Hôtellerie",
    description: "Hôtels, auberges, résidences et hébergements touristiques.",
    priority: "A",
    subcategories: [
      "Hôtels",
      "Auberges",
      "Guesthouses",
      "Résidences hôtelières",
      "Appart-hôtels",
      "Maisons d'hôtes",
      "Hébergements touristiques",
      "Résidences meublées",
      "Locations courte durée",
    ],
  },
  {
    id: "beaute",
    label: "Beauté et soins esthétiques",
    description: "Coiffure, barbiers, instituts, spas, onglerie et esthétique.",
    priority: "A",
    subcategories: [
      "Salons de coiffure",
      "Barbiers",
      "Coiffeurs",
      "Coiffeurs homme",
      "Coiffeurs femme",
      "Salons mixtes",
      "Salons afro",
      "Braiders",
      "Poseuses d'extensions",
      "Perruques",
      "Extensions capillaires",
      "Instituts de beauté",
      "Centres d'esthétique",
      "Esthétique",
      "Ongleries",
      "Manucure",
      "Pédicure",
      "Manucure / pédicure",
      "Nail salons",
      "Make-up artists",
      "Spas",
      "Centres de massage",
      "Massage",
      "Soins du visage",
      "Soins corporels",
      "Épilation",
    ],
  },
  {
    id: "mode-habillement",
    label: "Mode et habillement",
    description: "Boutiques de vêtements, couture, tissus, chaussures et accessoires.",
    priority: "A",
    subcategories: [
      "Boutiques de vêtements",
      "Boutiques homme",
      "Boutiques femme",
      "Boutiques enfants",
      "Haute couture",
      "Ateliers de couture",
      "Stylistes",
      "Créateurs de mode",
      "Tissus et pagnes",
      "Boutiques de chaussures",
      "Maroquineries",
      "Sacs et accessoires",
      "Lingerie",
      "Friperies",
      "Boutiques de mode africaine",
    ],
  },
  {
    id: "cosmetiques",
    label: "Cosmétiques et parfumerie",
    description: "Boutiques de cosmétiques, parfums et produits de soin.",
    priority: "A",
    subcategories: [
      "Boutiques de cosmétiques",
      "Parfumeries",
      "Boutiques de parfums",
      "Produits capillaires",
      "Produits de beauté",
      "Produits naturels",
      "Savonneries",
      "Boutiques de soins corporels",
    ],
  },
  {
    id: "commerces-specialises",
    label: "Commerces spécialisés",
    description: "Bijouteries, opticiens, fleuristes, librairies, mobilier, téléphonie.",
    priority: "A",
    subcategories: [
      "Bijouteries",
      "Horlogeries",
      "Opticiens",
      "Fleuristes",
      "Boutiques cadeaux",
      "Librairies",
      "Papeteries",
      "Magasins de jouets",
      "Articles pour bébés",
      "Articles de sport",
      "Magasins de décoration",
      "Mobilier",
      "Électroménager",
      "Magasins de téléphones",
      "Magasins informatiques",
      "Électronique",
      "Supermarchés",
      "Épiceries",
      "Supérettes",
      "Commerces alimentaires",
    ],
  },
  {
    id: "sante",
    label: "Santé",
    description: "Cliniques, pharmacies, cabinets dentaires, laboratoires, vétérinaires.",
    priority: "B",
    subcategories: [
      "Cliniques",
      "Centres médicaux",
      "Cabinets médicaux",
      "Médecins",
      "Cabinets dentaires",
      "Dentistes",
      "Laboratoires d'analyses",
      "Centres de santé",
      "Pharmacies",
      "Parapharmacies",
      "Opticiens",
      "Ophtalmologues",
      "Centres de kinésithérapie",
      "Centres de physiothérapie",
      "Nutritionnistes",
      "Centres de bien-être",
      "Cabinets infirmiers",
      "Centres spécialisés",
      "Vétérinaires",
    ],
  },
  {
    id: "immobilier",
    label: "Immobilier",
    description: "Agences, promoteurs, gestion locative, coworking et salles.",
    priority: "B",
    subcategories: [
      "Agences immobilières",
      "Promoteurs immobiliers",
      "Gestionnaires immobiliers",
      "Syndics",
      "Locations immobilières",
      "Locations de maisons",
      "Locations d'appartements",
      "Résidences",
      "Résidences meublées",
      "Terrains",
      "Vente immobilière",
      "Gestion locative",
      "Conciergerie",
      "Espaces de coworking",
      "Centres d'affaires",
      "Salles de réunion",
      "Espaces événementiels",
    ],
  },
  {
    id: "automobile",
    label: "Automobile et mobilité",
    description: "Garages, concessionnaires, pièces, lavage, motos, auto-écoles.",
    priority: "B",
    subcategories: [
      "Garages",
      "Concessionnaires automobiles",
      "Vente de véhicules",
      "Vente de véhicules d'occasion",
      "Pièces détachées",
      "Pneumatiques",
      "Vidange",
      "Centres auto",
      "Climatisation automobile",
      "Électricité automobile",
      "Carrosserie",
      "Peinture automobile",
      "Lavage automobile",
      "Centres de detailing",
      "Accessoires automobiles",
      "Vente de motos",
      "Réparation de motos",
      "Pièces détachées moto",
      "Accessoires moto",
      "Vente de vélos",
      "Réparation de vélos",
      "Location de voitures",
      "Location de motos",
      "Auto-écoles",
      "Services de dépannage",
      "Transport privé",
    ],
  },
  {
    id: "finance-juridique",
    label: "Finance, assurance et juridique",
    description: "Banques, microfinances, assurances, comptables, avocats, notaires.",
    priority: "C",
    subcategories: [
      "Banques",
      "Microfinances",
      "Institutions financières",
      "Services de paiement",
      "Assurances",
      "Courtiers en assurance",
      "Cabinets comptables",
      "Experts-comptables",
      "Cabinets d'audit",
      "Cabinets fiscaux",
      "Conseillers financiers",
      "Cabinets juridiques",
      "Avocats",
      "Notaires",
      "Huissiers",
      "Conseillers en gestion",
      "Sociétés de transfert d'argent",
      "Bureaux de change",
    ],
  },
  {
    id: "education",
    label: "Éducation et formation",
    description: "Écoles, universités, instituts et centres de formation.",
    priority: "B",
    subcategories: [
      "Écoles maternelles",
      "Écoles primaires privées",
      "Écoles secondaires privées",
      "Lycées",
      "Établissements internationaux",
      "Universités",
      "Instituts supérieurs",
      "Grandes écoles",
      "Centres de formation professionnelle",
      "Centres de formation informatique",
      "Écoles de langues",
      "Centres de formation en anglais",
      "Centres de formation en français",
      "Écoles de conduite",
      "Centres de soutien scolaire",
      "Cours particuliers",
      "Écoles de musique",
      "Écoles artistiques",
      "Centres de formation métiers",
      "Centres de formation numérique",
    ],
  },
  {
    id: "voyage-tourisme",
    label: "Voyage et tourisme",
    description: "Agences de voyage, tour-opérateurs, billetteries, guides.",
    priority: "B",
    subcategories: [
      "Agences de voyage",
      "Agences de tourisme",
      "Tour-opérateurs",
      "Billetteries",
      "Services de réservation",
      "Guides touristiques",
      "Excursions",
      "Circuits touristiques",
      "Transport touristique",
      "Hôtels",
      "Auberges",
      "Guesthouses",
      "Résidences touristiques",
      "Locations courte durée",
    ],
  },
  {
    id: "evenementiel",
    label: "Événementiel",
    description: "Agences événementielles, wedding planners, décorateurs, salles.",
    priority: "B",
    subcategories: [
      "Agences événementielles",
      "Wedding planners",
      "Organisateurs de mariages",
      "Organisateurs de cérémonies",
      "Décorateurs",
      "Location de matériel événementiel",
      "Location de tentes",
      "Location de chaises",
      "Location de tables",
      "Traiteurs",
      "Salles de réception",
      "Salles de conférence",
      "Photographes",
      "Vidéastes",
      "DJs",
      "Animateurs",
      "Groupes musicaux",
      "Studios",
      "Imprimeries",
      "Agences de communication événementielle",
    ],
  },
  {
    id: "communication-medias",
    label: "Communication, médias et création",
    description: "Agences de com', marketing, graphisme, studios, imprimeries.",
    priority: "C",
    subcategories: [
      "Agences de communication",
      "Agences marketing",
      "Agences digitales",
      "Agences publicitaires",
      "Community managers",
      "Graphistes",
      "Designers",
      "Studios photo",
      "Studios vidéo",
      "Photographes",
      "Vidéastes",
      "Agences branding",
      "Imprimeries",
      "Sérigraphies",
      "Agences médias",
      "Radios",
      "WebTV",
      "Créateurs de contenu",
      "Agences de relations publiques",
    ],
  },
  {
    id: "commerce-detail",
    label: "Commerce de détail",
    description: "Mode, maison, technologie et commerce général.",
    priority: "A",
    subcategories: [
      "Vêtements",
      "Chaussures",
      "Sacs",
      "Accessoires",
      "Bijoux",
      "Montres",
      "Lunettes",
      "Lingerie",
      "Tissus",
      "Pagnes",
      "Mode enfant",
      "Meubles",
      "Décoration",
      "Électroménager",
      "Literie",
      "Cuisine",
      "Articles ménagers",
      "Luminaires",
      "Rideaux",
      "Tapis",
      "Matériaux de décoration",
      "Téléphones",
      "Smartphones",
      "Ordinateurs",
      "Accessoires informatiques",
      "Électronique",
      "Jeux vidéo",
      "Consoles",
      "Réparation informatique",
      "Réparation de téléphones",
      "Supermarchés",
      "Supérettes",
      "Épiceries",
      "Boutiques alimentaires",
      "Boutiques spécialisées",
      "Magasins de proximité",
      "Boutiques cadeaux",
      "Fleuristes",
      "Librairies",
      "Papeteries",
      "Jouets",
      "Articles scolaires",
    ],
  },
  {
    id: "btp-construction",
    label: "BTP, construction et habitat",
    description: "Construction, architecture, menuiserie, électricité, matériaux.",
    priority: "C",
    subcategories: [
      "Entreprises de construction",
      "Entrepreneurs BTP",
      "Architectes",
      "Bureaux d'études",
      "Ingénieurs",
      "Décorateurs d'intérieur",
      "Architectes d'intérieur",
      "Menuiseries bois",
      "Menuiseries aluminium",
      "Métalliers",
      "Soudeurs",
      "Électriciens",
      "Plombiers",
      "Climatisation",
      "Carrelage",
      "Peinture bâtiment",
      "Quincailleries",
      "Matériaux de construction",
      "Entreprises de rénovation",
      "Entreprises d'étanchéité",
      "Entreprises de terrassement",
      "Aménagement paysager",
      "Jardineries",
      "Pépinières",
      "Cuisines aménagées",
      "Entreprises de nettoyage de chantier",
    ],
  },
  {
    id: "transport-logistique",
    label: "Transport, livraison et logistique",
    description: "Transport, livraison, coursiers, fret, déménagement, taxis.",
    priority: "C",
    subcategories: [
      "Entreprises de transport",
      "Transport de marchandises",
      "Transport de personnes",
      "Livraison",
      "Livraison de repas",
      "Coursiers",
      "Messagerie",
      "Transitaires",
      "Fret",
      "Logistique",
      "Entreposage",
      "Entrepôts",
      "Déménagement",
      "Location de véhicules",
      "Taxis",
      "Services de transport touristique",
      "Agences de transport interurbain",
      "Billetteries de transport",
    ],
  },
  {
    id: "technologie",
    label: "Technologie et numérique",
    description: "Agences web, développeurs, infogérance, réseaux, cloud.",
    priority: "C",
    subcategories: [
      "Agences web",
      "Développeurs",
      "Entreprises informatiques",
      "SaaS",
      "ESN",
      "Réparation informatique",
      "Réparation de téléphones",
      "Vente de matériel informatique",
      "Vente de logiciels",
      "Hébergement web",
      "Noms de domaine",
      "Cybersécurité",
      "Installation réseau",
      "Télécommunications",
      "Fournisseurs internet",
      "Solutions digitales",
      "Agences e-commerce",
      "Entreprises de transformation numérique",
      "Services cloud",
      "Centres de formation IT",
    ],
  },
  {
    id: "services-particuliers",
    label: "Services aux particuliers",
    description: "Nettoyage, pressing, jardinage, sécurité, dépannage à domicile.",
    priority: "C",
    subcategories: [
      "Entreprises de nettoyage",
      "Nettoyage à domicile",
      "Blanchisseries",
      "Pressings",
      "Services de repassage",
      "Services de ménage",
      "Garde d'enfants",
      "Services à domicile",
      "Jardinage",
      "Entretien des espaces verts",
      "Sécurité",
      "Gardiennage",
      "Serrurerie",
      "Désinfection",
      "Dératisation",
      "Désinsectisation",
      "Électricité",
      "Plomberie",
      "Climatisation",
      "Réparation électroménager",
    ],
  },
  {
    id: "animaux",
    label: "Animaux",
    description: "Vétérinaires, animaleries, toilettage, alimentation animale.",
    priority: "B",
    subcategories: [
      "Cabinets vétérinaires",
      "Cliniques vétérinaires",
      "Animaleries",
      "Toilettage animalier",
      "Alimentation animale",
      "Accessoires pour animaux",
      "Élevages",
      "Services animaliers",
      "Pension pour animaux",
    ],
  },
  {
    id: "agriculture",
    label: "Agriculture et agroalimentaire",
    description: "Fermes, coopératives, semences, boucheries, produits locaux.",
    priority: "C",
    subcategories: [
      "Fermes",
      "Exploitations agricoles",
      "Maraîchage",
      "Élevages",
      "Coopératives",
      "Producteurs agricoles",
      "Fournisseurs agricoles",
      "Semences",
      "Engrais",
      "Produits phytosanitaires",
      "Matériel agricole",
      "Aliments pour animaux",
      "Transformateurs agroalimentaires",
      "Producteurs alimentaires",
      "Boucheries",
      "Poissonneries",
      "Produits locaux",
      "Épiceries spécialisées",
      "Restaurants spécialisés en produits locaux",
      "Traiteurs",
    ],
  },
  {
    id: "loisirs-sport",
    label: "Loisirs, sport et divertissement",
    description: "Salles de sport, piscines, cinémas, cybercafés, loisirs.",
    priority: "B",
    subcategories: [
      "Salles de sport",
      "Fitness",
      "Musculation",
      "Centres sportifs",
      "Clubs de football",
      "Clubs de sport",
      "Piscines",
      "Centres de loisirs",
      "Parcs",
      "Aires de jeux",
      "Jeux vidéo",
      "Game centers",
      "Cybercafés",
      "Cinémas",
      "Discothèques",
      "Bars",
      "Karaokés",
      "Bowling",
      "Espaces de divertissement",
      "Clubs privés",
    ],
  },
  {
    id: "services-b2b",
    label: "Services professionnels B2B",
    description: "Conseil, RH, recrutement, comptabilité, marketing, coworking.",
    priority: "C",
    subcategories: [
      "Cabinets de conseil",
      "Consulting",
      "Ressources humaines",
      "Cabinets de recrutement",
      "Comptabilité",
      "Audit",
      "Fiscalité",
      "Conseil juridique",
      "Conseil en management",
      "Conseil financier",
      "Marketing",
      "Communication",
      "Agences digitales",
      "Sécurité",
      "Nettoyage professionnel",
      "Fournitures de bureau",
      "Centres d'affaires",
      "Coworking",
      "Secrétariat",
      "Impression professionnelle",
      "Formation professionnelle",
    ],
  },
  {
    id: "associations-ong",
    label: "Associations, ONG et organisations",
    description: "ONG, associations, fondations, organisations communautaires.",
    priority: "C",
    subcategories: [
      "ONG",
      "Associations",
      "Fondations",
      "Organisations communautaires",
      "Organisations professionnelles",
      "Organisations internationales",
      "Centres sociaux",
      "Organisations de jeunesse",
      "Organisations culturelles",
      "Organisations sportives",
      "Institutions religieuses",
      "Centres communautaires",
    ],
  },
] as const;

/* -------------------------------------------------------------------------- */
/* Résolution                                                                 */
/* -------------------------------------------------------------------------- */

/** Catégorie utilisée lorsqu'aucune n'est renseignée. */
export const FALLBACK_CATEGORY_ID = "services-b2b";

/** Retourne la définition d'une catégorie, ou `undefined` si l'identifiant est inconnu. */
export function getCategoryById(id: string | null | undefined): BusinessCategoryDef | undefined {
  if (!id) return undefined;
  return BUSINESS_CATEGORIES.find((category) => category.id === id);
}

/** Libellé d'une catégorie, avec repli lisible si l'identifiant est inconnu. */
export function getCategoryLabel(id: string | null | undefined): string {
  return getCategoryById(id)?.label ?? "Non classée";
}

/** Sous-catégories proposées pour une catégorie donnée. */
export function getSubcategories(id: string | null | undefined): readonly string[] {
  return getCategoryById(id)?.subcategories ?? [];
}

/**
 * Construit le libellé complet affiché partout : « Restauration › Maquis ».
 * Retourne « Non classée » si aucune catégorie n'est renseignée.
 */
export function formatCategoryLabel(
  categoryId: string | null | undefined,
  subcategory?: string | null,
): string {
  const category = getCategoryById(categoryId);
  if (!category) return "Non classée";
  if (subcategory && subcategory.trim() !== "") {
    return `${category.label} › ${subcategory}`;
  }
  return category.label;
}

/** Indique si un identifiant de catégorie existe dans le référentiel. */
export function isKnownCategoryId(id: string | null | undefined): boolean {
  return getCategoryById(id) !== undefined;
}
